config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :set_post, only: %i[ show new edit create update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new   
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    unless current_user == @comment.user
      redirect_to posts_url
    end
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_url(@post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_url(@post), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to post_url(@post), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :check_signed_in, only: %i[ new edit create update destroy ]

  def check_signed_in
    unless user_signed_in?
      redirect_to root_url
    end
  end

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    unless current_user == @post.user
      redirect_to posts_url
    end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Comment:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>By:</strong>
    <%= comment.user.email %>
  </p>

  <p>
    <strong> Post:</strong>
    <%= comment.post.content %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.hidden_field :post_id, value: @post.id %>
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment, post: @post %>

<br>

<div>
  <%= link_to "Back to posts", post_path(@post) %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", post_comment_path(comment.post.id, comment.id) %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_post_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", post: @post, comment: @comment %>

<br>

<div>
  <%= link_to "Back to post", post_path(@post) %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>
<% if current_user == @comment.user %>
<div>
  <%= button_to "Edit this comment", edit_post_comment_path(@post, @comment) %> |
  <%= button_to "Destroy this comment", post_comment_path, method: :delete %>
</div>
<% end %>
  <br>
<div>
  <%= link_to "Back to all posts", posts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evan's Blog Application</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

    <p>
    <strong>Publication Date:</strong>
    <%= post.created_at %>
  </p>

  <p>
    <strong>Created By:</strong>
    <%= post.user.email %>
  </p>

  <p>
    <strong>Comments:</strong>
    <% if post.comments.empty? %>
      No comments yet! 
    <% else %>
      <ul>
      <% post.comments.each do |c| %>
        <p> <li> <%= c.content %>  <p>
          <% if current_user == c.user %>
            <%= button_to "See comment details", post_comment_path(post_id: post.id, id: c.id), method: :get %>
          <% end %>
          </li> 
        <p> <strong> Written By: </strong> 
        <%= c.user.email %> </p>
        <p> <strong> Timestamp: </strong> 
        <%= c.created_at %> </p>
      <% end %>
      </ul>
    <% end %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <ol> 
  <% @posts.each do |post| %>
  <hr>
    <li> <%= render post %> </li>
    <%= button_to "See post details", post_path(post), method: :get %>
    <br>
    <% if user_signed_in? %>
      <%= button_to "Add comment", new_post_comment_path(post), method: :get %>
    <% end %>

  <% end %>
</ol>
</div>
<br>
<div>
<%= link_to "New post", new_post_path %> |
<%= link_to "Back to home", root_path %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>
<% if current_user == @post.user %>
  <div>
  <%= button_to "Edit this post", edit_post_path(@post) %>
  <%= button_to "Destroy this post", @post, method: :delete %>
</div>
<% end %>

<br>
<div>
<%= link_to "New post", new_post_path %> |
<%= link_to "Back to all posts", posts_path %> |
<%= link_to "Back to home", root_path %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to Evan's Blog Application!</h1>
<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div> 
 <br>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
  <br>
  <%= button_to "Create a new blog post", new_post_path, method: :get %>
<% else %>
  <%= button_to "Sign in to create a new blog post and comment", new_user_session_path, method: :get %> 
<% end %>
<br>
<%= button_to "See all blog posts", posts_path, method: :get %>